<?php 
include_once __DIR__."/components/head.phtml";
?>

<body class="bg-zinc-50">
    <div class="md:flex md:items-center md:justify-center md:h-screen p-4">
        <div class="">
            <div class="flex flex-col md:flex md:flex-row md:items-center md:gap-12">
                <div class="md:col-span-1">
                    <div class="px-4 sm:px-0">
                        <img src="http:://localhost/tp/images/login.svg" alt="illustration inscription">
                    </div>
                </div>
                <div class="mt-5 md:col-span-2 md:mt-0">
                    <h1 class="text-emerald-700 text-center font-bold text-xl mb-4">Connexion</h1>
                    <form action="" method="POST" class="md:mt-16">
                        <div>
                            <?= $error ?? null ?>
                        </div>
                        <div class="overflow-hidden shadow sm:rounded-md">
                            <div class="bg-white flex flex-col gap-10 px-4 py-10 sm:p-6">
                                <div class="col-span-6 sm:col-span-3">
                                    <label for="mail" class="block text-md font-medium text-gray-700">Email</label>
                                    <input type="email" name="mail" id="mail" aria-describedby="mail-format"
                                        autocomplete="off" placeholder="adresse email"
                                        value="<?= $_SESSION['email'] ?? null?>"
                                        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500 sm:text-md">
                                    <p class="mt-2 hidden text-sm text-gray-500" id="mail-format">
                                        Exemple: mouhamed845@gmail.com
                                    </p>
                                    <span id="error-mail" class="hidden mt-2 text-red-500"></span>
                                    <span id="email-ok" class="hidden mt-2 text-emerald-500 flex items-center">
                                        ok <i class="fa-solid fa-check ml-1"></i>
                                    </span>
                                </div>
                                <div class="col-span-6 sm:col-span-3">
                                    <label for="password" class="block text-md font-medium text-gray-700">Mot de
                                        passe</label>
                                    <div class="relative mb-6">
                                        <input value="<?= $_SESSION['password'] ?? null?>" type="password"
                                            name="password" id="password" placeholder="mot de passe"
                                            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500 sm:text-md">
                                        <div class="flex absolute inset-y-0 right-0 items-center pr-3">
                                            <i class="fa-regular fa-eye cursor-pointer" id="password-handler"></i>
                                        </div>
                                    </div>
                                    <span id="error-password" class="hidden mt-2 text-red-500"></span>
                                    <span id="password-ok" class="hidden mt-2 text-emerald-500 flex items-center ">
                                        ok <i class="fa-solid fa-check ml-1"></i>
                                    </span>
                                </div>
                                <div class="px-0 py-3 text-right sm:px-0 flex md:gap-20 justify-between items-center">
                                    <div class="flex flex-col gap-2 items-start">
                                        <span class="text-md">Pas encore de compte</span>
                                        <span class="text-emerald-700 no-underline hover:underline">
                                            <a href="/tp/inscription">S'inscrire</a>
                                        </span>
                                    </div>
                                    <button data-tooltip-target="tooltip-animation" type="submit" id="connexion"
                                        class="inline-flex justify-center rounded-md border border-transparent bg-emerald-500 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-emerald-700 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-offset-2">Se
                                        connecter</button>

                                    <!--  <button data-tooltip-target="tooltip-default" type="button"
                                        class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Default
                                        tooltip</button> -->
                                    <div id="tooltip-animation" role="tooltip"
                                        class="inline-block absolute invisible z-10 py-2 px-3 text-sm font-medium text-white bg-gray-900 rounded-lg shadow-sm opacity-0 transition-opacity duration-300 tooltip dark:bg-gray-700"
                                        style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(0px, 8px);"
                                        data-popper-reference-hidden="" data-popper-escaped=""
                                        data-popper-placement="bottom">
                                        Veuillez d'abord remplir correctement tous les champs avant de soumettre
                                        <div class="tooltip-arrow" data-popper-arrow=""
                                            style="position: absolute; left: 0px; transform: translate(0px);"></div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="http:://localhost/tp/js/connexion.js"></script>
</body>

</html>