<?php include_once __DIR__."/components/head.phtml"; ?>

<body>
    <div class="md:flex md:items-center md:justify-center md:h-screen p-4">
        <div class="">
            <div class="flex flex-col md:flex md:flex-row md:items-end md:gap-12">
                <div class="md:col-span-1">
                    <div class="px-4 sm:px-0">
                        <img src="http:://localhost/tp/images/signup.svg" alt="illustration inscription">
                    </div>
                </div>
                <div class="mt-5 md:col-span-2 md:mt-0">
                    <h1 class="text-emerald-700 text-center font-bold text-xl mb-4">Inscription</h1>
                    <form action="" method="POST" enctype="multipart/form-data">
                        <div>
                            <!-- <button id="toggle-modal"
                                class="hidden text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                                type="button" data-modal-toggle="popup-modal">
                                Toggle modal
                            </button> -->
                            <?= $error ?? null ?>
                        </div>
                        <div class="overflow-hidden shadow sm:rounded-md">
                            <div class="bg-white px-4 py-5 sm:p-6">
                                <div class="grid grid-cols-6 gap-6">
                                    <div class="col-span-6 sm:col-span-3">
                                        <label for="first-name"
                                            class="block text-sm font-medium text-gray-700">Nom</label>
                                        <input type="text" name="first-name" id="first-name" autocomplete="off"
                                            value="<?= $_SESSION['nom'] ?? null?>"
                                            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500 sm:text-sm">
                                        <span id="error-nom" class="hidden mt-2 text-red-500"></span>
                                        <span id="nom-ok" class="hidden mt-2 text-emerald-500 ">ok</span>
                                    </div>

                                    <div class="col-span-6 sm:col-span-3">
                                        <label for="last-name"
                                            class="block text-sm font-medium text-gray-700">Prenom</label>
                                        <input type="text" name="last-name" id="last-name" autocomplete="off"
                                            value="<?= $_SESSION['prenom'] ?? null?>"
                                            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500 sm:text-sm">
                                        <span id="error-prenom" class="hidden mt-2 text-red-500"></span>
                                        <span id="prenom-ok" class="hidden mt-2 text-emerald-500 ">ok</span>
                                    </div>

                                    <div class="col-span-6 sm:col-span-3">
                                        <label for="email" class="block text-sm font-medium text-gray-700">Adresse
                                            email</label>
                                        <input type="email" name="email" id="email" autocomplete="off"
                                            value="<?= $_SESSION['email'] ?? null?>"
                                            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500 sm:text-sm">
                                        <p class="mt-2 hidden text-sm text-gray-500" id="mail-format">
                                            Exemple: mouhamed845@gmail.com
                                        </p>
                                        <span id="error-mail" class="hidden mt-2 text-red-500"></span>
                                        <span id="email-ok" class="hidden mt-2 text-emerald-500 ">ok</span>
                                    </div>

                                    <div class="col-span-6 sm:col-span-3">
                                        <label for="role" class="block text-sm font-medium text-gray-700">Role</label>
                                        <select id="role" name="role"
                                            class="mt-1 block w-full rounded-md border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-emerald-500 focus:outline-none focus:ring-emerald-500 sm:text-sm">
                                            <option selected></option>
                                            <option value="Admin">Admin</option>
                                            <option value="User">User</option>
                                        </select>
                                        <span id="error-role" class="hidden mt-2 text-red-500"></span>
                                        <span id="role-ok" class="hidden mt-2 text-emerald-500 ">ok</span>
                                    </div>
                                    <div class="col-span-6 sm:col-span-3">
                                        <label for="password" class="block text-sm font-medium text-gray-700">Mot de
                                            passe</label>
                                        <div class="relative mb-6">
                                            <input type="password" name="password" id="password"
                                                value="<?= $_SESSION['password'] ?? null?>" placeholder="mot de passe"
                                                autocomplete="off"
                                                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500 sm:text-md">
                                            <div class="flex absolute inset-y-0 right-0 items-center pr-3">
                                                <i class="fa-regular fa-eye cursor-pointer" id="password-handler"></i>
                                            </div>
                                        </div>
                                        <span id="error-password" class="hidden mt-2 text-red-500"></span>
                                        <span id="password-ok" class="hidden mt-2 text-emerald-500 ">ok</span>
                                    </div>

                                    <div class="col-span-6 sm:col-span-3">
                                        <label for="confirm-password"
                                            class="block text-sm font-medium text-gray-700">Confirmer
                                            mot de passe</label>
                                        <div class="relative mb-6">
                                            <input type="password" name="confirm-password" id="confirm-password"
                                                value="<?= $_SESSION['password'] ?? null?>" placeholder="mot de passe"
                                                autocomplete="off"
                                                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500 sm:text-md">
                                            <div class="flex absolute inset-y-0 right-0 items-center pr-3">
                                                <i class="fa-regular fa-eye cursor-pointer"
                                                    id="confirm-password-handler"></i>
                                            </div>
                                        </div>
                                        <span id="error-confirm-password" class="hidden mt-2 text-red-500"></span>
                                        <span id="confirm-password-ok" class="hidden mt-2 text-emerald-500 ">ok</span>
                                    </div>
                                    <div class="col-span-6 sm:col-span-3">
                                        <label for="photo" class="block text-sm font-medium text-gray-700">Photo</label>
                                        <input type="file" class="
                                        file:bg-emerald-500
                                        file:px-4 file:py-2
                                        file:border-none
                                        file:rounded-md
                                        file:text-white
                                        file:cursor-pointer
                            
                                        text-zinc-800
                                        rounded-md
                                        pr-2
                                        cursor-pointer
                                        " id="file_input" name="photo">
                                    </div>

                                </div>
                            </div>
                            <div class="bg-gray-50 px-4 py-3 text-right sm:px-6 flex justify-between items-center">
                                <div class="flex flex-col gap-2 items-start">
                                    <span>Déjà un compte</span>
                                    <span class="text-emerald-700 no-underline hover:underline">
                                        <a href="/tp/">Connexion</a>
                                    </span>
                                </div>
                                <button type="submit" id="inscription" data-tooltip-target="tooltip-animation"
                                    class="inline-flex justify-center rounded-md border border-transparent bg-emerald-500 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-emerald-700 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-offset-2">S'inscrire</button>
                                <div id="tooltip-animation" role="tooltip"
                                    class="inline-block absolute invisible z-10 py-2 px-3 text-sm font-medium text-white bg-gray-900 rounded-lg shadow-sm opacity-0 transition-opacity duration-300 tooltip dark:bg-gray-700"
                                    style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(0px, 8px);"
                                    data-popper-reference-hidden="" data-popper-escaped=""
                                    data-popper-placement="bottom">
                                    Veuillez d'abord remplir correctement tous les champs avant de soumettre
                                    <div class="tooltip-arrow" data-popper-arrow=""
                                        style="position: absolute; left: 0px; transform: translate(0px);"></div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="http:://localhost/tp/js/inscription.js"></script>
</body>

</html>