<table class="w-full text-sm text-left text-gray-500">
    <thead class="text-xs text-white uppercase bg-emerald-600">
        <tr>
            <th scope="col" class="py-3 px-6">
                Matricule
            </th>
            <th scope="col" class="py-3 px-6">
                Nom
            </th>
            <th scope="col" class="py-3 px-6">
                Prenom
            </th>
            <th scope="col" class="py-3 px-6">
                Date archivage
            </th>
            <th scope="col" class="py-3 px-6">
                Role
            </th>
            <th scope="col" class="py-3 px-6">
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach ($users as $key => $user):
                if ((int) $key % 2 === 0):
        ?>
        <tr class="bg-white border-b">
            <?php include "adminTableDraftedRowContent.phtml" ?>
        </tr>
        <?php
                else:
        ?>
        <tr class="bg-white border-b bg-zinc-100">
            <?php include "adminTableDraftedRowContent.phtml" ?>
        </tr>
        <?php
                endif;
            endforeach;
        ?>
    </tbody>
</table>

<div id="tooltip-undraft" role="tooltip"
    class="inline-block absolute invisible z-10 py-2 px-3 text-sm font-medium text-white bg-gray-900 rounded-lg shadow-sm opacity-0 transition-opacity duration-300 tooltip dark:bg-gray-700"
    style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(0px, 8px);"
    data-popper-reference-hidden="" data-popper-escaped="" data-popper-placement="bottom">
    Désarchiver
    <div class="tooltip-arrow" data-popper-arrow="" style="position: absolute; left: 0px; transform: translate(0px);">
    </div>
</div>