<?php 
    $path = include(__DIR__."/../../Utils/getCurrentPath.php");
    $linkFocusClasses = "text-white bg-emerald-700 rounded md:bg-transparent md:text-emerald-700 md:p-0";
    $linkBlurClasses = "text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-emerald-700 md:p-0";
?>
<nav class="bg-emerald-600 border-gray-200 px-2 sm:px-4 py-2.5">
    <div class="container flex flex-wrap justify-between items-center mx-auto">
        <button id="dropdownAvatarNameButton" data-dropdown-toggle="dropdownAvatarName">
            <div class="flex items-center space-x-4">
                <?php
                if ($_SESSION['photo']):
            ?>
                <img id="profileImage"
                    class="p-1 w-10 h-10 rounded-full ring-4 <?= $_SESSION['role'] === "Admin" ? "ring-emerald-800" : "ring-red-300"?>"
                    src="<?= 'data:image/jpeg;base64,'.base64_encode($_SESSION['photo']) ?>" alt="">
                <?php else: ?>
                <img id="profileImage"
                    class="wp-1 w-10 h-10 rounded-full ring-4 <?= $_SESSION['role'] === "Admin" ? "ring-emerald-800" : "ring-red-300"?>"
                    src="http:://localhost/tp/images/avatar.svg" alt="">
                <?php endif; ?>
                <div class="font-medium">
                    <div class="text-white"><?= $_SESSION['fullname']?></div>
                    <div class="text-sm text-white opacity-70"><?= $_SESSION['matricule'] ?></div>
                </div>

                <svg class="w-4 h-4 mx-1.5" aria-hidden="true" fill="#fff" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                        clip-rule="evenodd"></path>
                </svg>
            </div>
        </button>
        <button data-collapse-toggle="navbar-default" type="button"
            class="inline-flex items-center p-2 ml-3 text-sm text-white rounded-lg md:hidden hover:bg-transparent focus:outline-none focus:ring-2 focus:ring-white"
            aria-controls="navbar-default" aria-expanded="false">
            <span class="sr-only">Ouvrir menu principal</span>
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                    d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                    clip-rule="evenodd"></path>
            </svg>
        </button>
        <div class="hidden w-full md:block md:w-auto" id="navbar-default">
            <ul
                class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white">
                <li>
                    <a href="<?= $_SESSION['role'] === "Admin" ? "admin" : "user"?>"
                        class="block py-2 pr-4 pl-3 <?= $path === "admin" || $path === "user" ? $linkFocusClasses : $linkBlurClasses?>"
                        aria-current="page">Liste employe</a>
                </li>
                <li>
                    <a href="<?= $_SESSION['role'] === "Admin" ? "archives" : "userArchives"?>"
                        class="block py-2 pr-4 pl-3 <?= $path === "archives" || $path === "userArchives" ? $linkFocusClasses : $linkBlurClasses?>">Liste
                        archivés</a>
                </li>
                <li>
                    <a href="logout"
                        class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-emerald-700 md:p-0">
                        <i class="fa-solid fa-arrow-right-from-bracket"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Dropdown menu -->
<div id="dropdownAvatarName" class="hidden z-10 w-52 bg-zinc-50 rounded divide-y divide-gray-100 shadow shadow-lg"
    style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(0px, 1216px);"
    data-popper-reference-hidden="" data-popper-escaped="" data-popper-placement="bottom">
    <div class="py-3 px-4 text-sm text-gray-900">
        <div class="font-bold <?= $_SESSION['role'] === "Admin" ? "text-emerald-800" : "text-red-400"?>">
            <?=$_SESSION['role']?></div>
        <div class="truncate"><?=$_SESSION['email']?></div>
    </div>
    <ul class="py-1 text-sm text-gray-700" aria-labelledby="dropdownInformdropdownAvatarNameButtonationButton">
        <li>
            <a href="#" data-modal-toggle="authentication-modal"
                class="flex group items-center py-2 px-4 hover:bg-emerald-600 hover:text-white hover:font-semi-bold">
                <svg class="fill-gray-700 group-hover:fill-white" width="16" height="16" version="1.1" id="Layer_1"
                    xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                    viewBox="0 0 485.017 485.017" style="enable-background:new 0 0 485.017 485.017; color: inherit;"
                    xml:space="preserve">
                    <g>
                        <path d="M361.205,68.899c-14.663,0-28.447,5.71-38.816,16.078c-21.402,21.403-21.402,56.228,0,77.631
		c10.368,10.368,24.153,16.078,38.815,16.078s28.447-5.71,38.816-16.078c21.402-21.403,21.402-56.228,0-77.631
		C389.652,74.609,375.867,68.899,361.205,68.899z M378.807,141.394c-4.702,4.702-10.953,7.292-17.603,7.292
		s-12.901-2.59-17.603-7.291c-9.706-9.706-9.706-25.499,0-35.205c4.702-4.702,10.953-7.291,17.603-7.291s12.9,2.589,17.603,7.291
		C388.513,115.896,388.513,131.688,378.807,141.394z" />
                        <path d="M441.961,43.036C414.21,15.284,377.311,0,338.064,0c-39.248,0-76.146,15.284-103.897,43.036
		c-42.226,42.226-54.491,105.179-32.065,159.698L0.254,404.584l-0.165,80.268l144.562,0.165v-55.722h55.705l0-55.705h55.705v-64.492
		l26.212-26.212c17.615,7.203,36.698,10.976,55.799,10.976c39.244,0,76.14-15.282,103.889-43.032
		C499.25,193.541,499.25,100.325,441.961,43.036z M420.748,229.617c-22.083,22.083-51.445,34.245-82.676,34.245
		c-18.133,0-36.237-4.265-52.353-12.333l-9.672-4.842l-49.986,49.985v46.918h-55.705l0,55.705h-55.705v55.688l-84.5-0.096
		l0.078-37.85L238.311,208.95l-4.842-9.672c-22.572-45.087-13.767-99.351,21.911-135.029C277.466,42.163,306.83,30,338.064,30
		c31.234,0,60.598,12.163,82.684,34.249C466.34,109.841,466.34,184.025,420.748,229.617z" />
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                </svg>
                <span class="ml-1"> Modifier mot de passe</span>
            </a>
        </li>
        <li>
            <a href="#" data-modal-toggle="update-photo-modal"
                class="block py-2 px-4 hover:bg-emerald-600 hover:text-white hover:font-semi-bold">
                <i class="fa-regular fa-image mr-1"></i>Modifier photo profil</a>
        </li>
    </ul>
    <div class="py-1">
        <a href="logout"
            class="block py-2 px-4 text-sm text-gray-700 hover:bg-emerald-600 hover:text-white hover:font-semi-bold">
            <i class="fa-solid fa-arrow-right-from-bracket mr-1"></i>Deconnexion
        </a>
    </div>
</div>

<?php include_once "update-password-modal.phtml"; ?>
<?php include_once "update-photo-modal.phtml"; ?>