<div class="flex justify-center">

    <nav aria-label="Page navigation example"
        class="mt-6 flex justify-center items-center sm:justify-center fixed sm:bottom-80 bottom-30">
        <?php
            $linkPrev = "$path?page=$prevPage";
            $linkSuiv = "$path?page=$nextPage";
        ?>
        <!-- Previous Button -->
        <a <?= $prevPage !== 0.0 ? "href='$linkPrev'" : "role='link' aria-diasabled='true'" ?>
            class="inline-flex items-center py-2 px-4 mr-3 text-sm font-medium text-white bg-emerald-600 rounded-lg border border-emerald-300 hover:bg-emerald-100 hover:text-gray-700">
            <svg aria-hidden="true" class="mr-2 w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                    d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z"
                    clip-rule="evenodd"></path>
            </svg>
            Precedent
        </a>
        <span class="mr-3 text-lg text-emerald-600 font-bold px-4 py-2 bg-emerald-100 rounded">
            <?= $page.' <span class="text-zinc-700">/ '. $numPages .'</span>' ?>
        </span>
        <a <?= $nextPage <= $numPages ? "href='$linkSuiv'" : "role='link' aria-diasabled='true'" ?>
            class="inline-flex items-center py-2 px-4 mr-3 text-sm font-medium text-white bg-emerald-600 rounded-lg border border-emerald-300 hover:bg-emerald-100 hover:text-gray-700">
            Suivant
            <svg aria-hidden="true" class="ml-2 w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                    d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z"
                    clip-rule="evenodd"></path>
            </svg>
        </a>

    </nav>
</div>