<!-- Modal toggle -->
<!-- <button
    class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
    type="button" data-modal-toggle="authentication-modal">
    Toggle modal
</button> -->

<!-- Main modal -->
<div id="update-photo-modal" tabindex="-1" aria-hidden="true"
    class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full justify-center items-center">
    <div class="relative p-4 w-full max-w-md h-full md:h-auto">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow">
            <button type="button" id="up-photo-close-modal"
                class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center"
                data-modal-toggle="update-photo-modal">
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                        clip-rule="evenodd"></path>
                </svg>
                <span class="sr-only">Close modal</span>
            </button>
            <div class="py-6 px-6 lg:px-8">
                <div class="flex flex-col justify-center items-center mb-4">
                    <h3 class="mb-4 text-xl font-medium text-gray-900">Modifier photo</h3>
                    <?php
                        if ($_SESSION['photo']):
                    ?>
                    <img id="modalImage"
                        class="p-1 w-10 h-10 rounded-full ring-4 <?= $_SESSION['role'] === "Admin" ? "ring-emerald-800" : "ring-red-300"?>"
                        src="<?= 'data:image/jpeg;base64,'.base64_encode($_SESSION['photo']) ?>" alt="">
                    <?php else: ?>
                    <img id="modalImage"
                        class="wp-1 w-10 h-10 rounded-full ring-4 <?= $_SESSION['role'] === "Admin" ? "ring-emerald-800" : "ring-red-300"?>"
                        src="http:://localhost/tp/images/avatar.svg" alt="">
                    <?php endif; ?>
                </div>
                <div id="up-photo-server-message" class="mb-2"></div>
                <form id="update-photo" class="space-y-6" enctype="multipart/form-data" method="post">
                    <div class="col-span-6 sm:col-span-3">
                        <label for="photo" class="block text-sm font-medium text-gray-700 mb-1">Choisissez une
                            Photo</label>
                        <input type="file" class="
                                        file:bg-emerald-500
                                        file:px-4 file:py-2
                                        file:border-none
                                        file:rounded-md
                                        file:text-white
                                        file:cursor-pointer
                            
                                        text-zinc-800
                                        rounded-md
                                        pr-2
                                        cursor-pointer
                                        " id="file_input" name="photo">
                    </div>
                    <button type="submit"
                        class="w-full text-white bg-emerald-700 hover:bg-emerald-800 focus:ring-4 focus:outline-none focus:ring-emerald-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Modifier</button>
                </form>
            </div>
        </div>
    </div>
</div>